#!  /bin/bash
#RM_SELINUX_RULE=enable
#
#  PRNL=
#  PRNC=
#  PRNP=dcpt420wpdrv-3.5.0-1a.i386.deb
#  SCAN=brscan5-1.3.10-5.amd64.deb
#  SKEY=brscan-skey-0.3.2-0.amd64.deb
#
if ! [ -f /etc/init.d/cupsys ];then
 DUMMYCUPSYS=1
 ln -s /bin/true  /etc/init.d/cupsys
fi
if ! [ -f /etc/init.d/cups ];then
 DUMMYCUPS=1
 ln -s /bin/true  /etc/init.d/cups
fi
if ! [ -f /etc/init.d/lpd ];then
 DUMMYLPD=1
 ln -s /bin/true  /etc/init.d/lpd
fi
if ! [ -f /etc/init.d/lprng ];then
 DUMMYLPRNG=1
 ln -s /bin/true  /etc/init.d/lprng
fi
dpkg  -x dcpt420wpdrv-3.5.0-1.i386.deb /
dpkg  -P    dcpt420wpdrv
if [ "$DUMMYCUPS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cups  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cups
  fi
fi

if [ "$DUMMYCUPSYS" = 1 ];then
  lsc=$(ls -al /etc/init.d/cupsys  2> /dev/null| grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/cupsys
  fi
fi

if [ "$DUMMYLPD" = 1 ];then
  lsc=$(ls -al /etc/init.d/lpd  2> /dev/null | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lpd
  fi
fi

if [ "$DUMMYLPRNG" = 1 ];then
  lsc=$(ls -al /etc/init.d/lprng | grep ^l)
  if [ "$lsc" != "" ];then
    rm -f /etc/init.d/lprng
  fi
fi


