[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "vite --port 5173 --host"
  port = 8888
  targetPort = 5173
  framework = "#static"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
