[build]
  command = "npm run build"
  publish = "dist"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["googleapis"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
